coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5%
    patch:
      default:
        target: auto
        threshold: 5%

ignore:
  - "imgui-platform-kit/examples"
  - "imgui-platform-kit/tests"
